### ISSUE TITLE
Light Refactor Error (module not defined)

### ISSUE THREAD

**Issue by Hirse** [asgerf/bracket-rename#6]
Your extension doesn't seem to work anymore due to an error with the light refactor module you are using. This might be because of the recent Brackets 1.1 Update as I think it was working well before and another extension seems to have a similar error.
(Tested on Win 7 and 8, both Brackets 1.1)
![bug_brackets_rename](https://cloud.githubusercontent.com/assets/2564094/5660111/8f2e8e7e-971c-11e4-837d-90d5f54b47b7.PNG)

**Comment by Hirse** [comment]
I had the same error also in another extension and found after some searching that both were cause by the latest version of the CSSLint extension.
I have submitted an [issue there](https://github.com/cfjedimaster/brackets-csslint/issues/35).
Sorry for the wrong issue.

**Comment by asgerf** [comment]
No worries :)
